/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimingRouteImport } from './routes/timing'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as MapRouteImport } from './routes/map'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as IndexRouteImport } from './routes/index'

const TimingRoute = TimingRouteImport.update({ id: '/timing', path: '/timing', getParentRoute: () => rootRouteImport } as any)
const SnapshotsRoute = SnapshotsRouteImport.update({ id: '/snapshots', path: '/snapshots', getParentRoute: () => rootRouteImport } as any)
const ReflectionsRoute = ReflectionsRouteImport.update({ id: '/reflections', path: '/reflections', getParentRoute: () => rootRouteImport } as any)
const WorkflowsRoute = WorkflowsRouteImport.update({ id: '/workflows', path: '/workflows', getParentRoute: () => rootRouteImport } as any)
const MapRoute = MapRouteImport.update({ id: '/map', path: '/map', getParentRoute: () => rootRouteImport } as any)
const ModesRoute = ModesRouteImport.update({ id: '/modes', path: '/modes', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modes': typeof ModesRoute
  '/map': typeof MapRoute
  '/workflows': typeof WorkflowsRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/timing': typeof TimingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modes': typeof ModesRoute
  '/map': typeof MapRoute
  '/workflows': typeof WorkflowsRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/timing': typeof TimingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modes': typeof ModesRoute
  '/map': typeof MapRoute
  '/workflows': typeof WorkflowsRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/timing': typeof TimingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modes' | '/map' | '/workflows' | '/reflections' | '/snapshots' | '/timing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modes' | '/map' | '/workflows' | '/reflections' | '/snapshots' | '/timing'
  id: '__root__' | '/' | '/modes' | '/map' | '/workflows' | '/reflections' | '/snapshots' | '/timing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModesRoute: typeof ModesRoute
  MapRoute: typeof MapRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ReflectionsRoute: typeof ReflectionsRoute
  SnapshotsRoute: typeof SnapshotsRoute
  TimingRoute: typeof TimingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timing': { id: '/timing'; path: '/timing'; fullPath: '/timing'; preLoaderRoute: typeof TimingRouteImport; parentRoute: typeof rootRouteImport }
    '/snapshots': { id: '/snapshots'; path: '/snapshots'; fullPath: '/snapshots'; preLoaderRoute: typeof SnapshotsRouteImport; parentRoute: typeof rootRouteImport }
    '/reflections': { id: '/reflections'; path: '/reflections'; fullPath: '/reflections'; preLoaderRoute: typeof ReflectionsRouteImport; parentRoute: typeof rootRouteImport }
    '/workflows': { id: '/workflows'; path: '/workflows'; fullPath: '/workflows'; preLoaderRoute: typeof WorkflowsRouteImport; parentRoute: typeof rootRouteImport }
    '/map': { id: '/map'; path: '/map'; fullPath: '/map'; preLoaderRoute: typeof MapRouteImport; parentRoute: typeof rootRouteImport }
    '/modes': { id: '/modes'; path: '/modes'; fullPath: '/modes'; preLoaderRoute: typeof ModesRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, ModesRoute, MapRoute, WorkflowsRoute, ReflectionsRoute, SnapshotsRoute, TimingRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
