/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TwoeRouteImport } from './routes/twoe'
import { Route as TimingRouteImport } from './routes/timing'
import { Route as SparkRouteImport } from './routes/spark'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoomRouteImport } from './routes/loom'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TwoeIndexRouteImport } from './routes/twoe.index'
import { Route as SparkIndexRouteImport } from './routes/spark.index'
import { Route as LoomIndexRouteImport } from './routes/loom.index'
import { Route as TwoeResultsRouteImport } from './routes/twoe.results'
import { Route as TwoeAssessmentRouteImport } from './routes/twoe.assessment'
import { Route as SparkReflectRouteImport } from './routes/spark.reflect'
import { Route as SparkMirrorRouteImport } from './routes/spark.mirror'
import { Route as SparkCurrentsRouteImport } from './routes/spark.currents'
import { Route as LoomConstellationRouteImport } from './routes/loom.constellation'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoeRoute = TwoeRouteImport.update({
  id: '/twoe',
  path: '/twoe',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingRoute = TimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkRoute = SparkRouteImport.update({
  id: '/spark',
  path: '/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoomRoute = LoomRouteImport.update({
  id: '/loom',
  path: '/loom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoeIndexRoute = TwoeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TwoeRoute,
} as any)
const SparkIndexRoute = SparkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SparkRoute,
} as any)
const LoomIndexRoute = LoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoomRoute,
} as any)
const TwoeResultsRoute = TwoeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TwoeRoute,
} as any)
const TwoeAssessmentRoute = TwoeAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => TwoeRoute,
} as any)
const SparkReflectRoute = SparkReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => SparkRoute,
} as any)
const SparkMirrorRoute = SparkMirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => SparkRoute,
} as any)
const SparkCurrentsRoute = SparkCurrentsRouteImport.update({
  id: '/currents',
  path: '/currents',
  getParentRoute: () => SparkRoute,
} as any)
const LoomConstellationRoute = LoomConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => LoomRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loom': typeof LoomRouteWithChildren
  '/map': typeof MapRoute
  '/modes': typeof ModesRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/spark': typeof SparkRouteWithChildren
  '/timing': typeof TimingRoute
  '/twoe': typeof TwoeRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/loom/constellation': typeof LoomConstellationRoute
  '/spark/currents': typeof SparkCurrentsRoute
  '/spark/mirror': typeof SparkMirrorRoute
  '/spark/reflect': typeof SparkReflectRoute
  '/twoe/assessment': typeof TwoeAssessmentRoute
  '/twoe/results': typeof TwoeResultsRoute
  '/loom/': typeof LoomIndexRoute
  '/spark/': typeof SparkIndexRoute
  '/twoe/': typeof TwoeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/modes': typeof ModesRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/timing': typeof TimingRoute
  '/workflows': typeof WorkflowsRoute
  '/loom/constellation': typeof LoomConstellationRoute
  '/spark/currents': typeof SparkCurrentsRoute
  '/spark/mirror': typeof SparkMirrorRoute
  '/spark/reflect': typeof SparkReflectRoute
  '/twoe/assessment': typeof TwoeAssessmentRoute
  '/twoe/results': typeof TwoeResultsRoute
  '/loom': typeof LoomIndexRoute
  '/spark': typeof SparkIndexRoute
  '/twoe': typeof TwoeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loom': typeof LoomRouteWithChildren
  '/map': typeof MapRoute
  '/modes': typeof ModesRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/spark': typeof SparkRouteWithChildren
  '/timing': typeof TimingRoute
  '/twoe': typeof TwoeRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/loom/constellation': typeof LoomConstellationRoute
  '/spark/currents': typeof SparkCurrentsRoute
  '/spark/mirror': typeof SparkMirrorRoute
  '/spark/reflect': typeof SparkReflectRoute
  '/twoe/assessment': typeof TwoeAssessmentRoute
  '/twoe/results': typeof TwoeResultsRoute
  '/loom/': typeof LoomIndexRoute
  '/spark/': typeof SparkIndexRoute
  '/twoe/': typeof TwoeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loom'
    | '/map'
    | '/modes'
    | '/reflections'
    | '/snapshots'
    | '/spark'
    | '/timing'
    | '/twoe'
    | '/workflows'
    | '/loom/constellation'
    | '/spark/currents'
    | '/spark/mirror'
    | '/spark/reflect'
    | '/twoe/assessment'
    | '/twoe/results'
    | '/loom/'
    | '/spark/'
    | '/twoe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/modes'
    | '/reflections'
    | '/snapshots'
    | '/timing'
    | '/workflows'
    | '/loom/constellation'
    | '/spark/currents'
    | '/spark/mirror'
    | '/spark/reflect'
    | '/twoe/assessment'
    | '/twoe/results'
    | '/loom'
    | '/spark'
    | '/twoe'
  id:
    | '__root__'
    | '/'
    | '/loom'
    | '/map'
    | '/modes'
    | '/reflections'
    | '/snapshots'
    | '/spark'
    | '/timing'
    | '/twoe'
    | '/workflows'
    | '/loom/constellation'
    | '/spark/currents'
    | '/spark/mirror'
    | '/spark/reflect'
    | '/twoe/assessment'
    | '/twoe/results'
    | '/loom/'
    | '/spark/'
    | '/twoe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoomRoute: typeof LoomRouteWithChildren
  MapRoute: typeof MapRoute
  ModesRoute: typeof ModesRoute
  ReflectionsRoute: typeof ReflectionsRoute
  SnapshotsRoute: typeof SnapshotsRoute
  SparkRoute: typeof SparkRouteWithChildren
  TimingRoute: typeof TimingRoute
  TwoeRoute: typeof TwoeRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twoe': {
      id: '/twoe'
      path: '/twoe'
      fullPath: '/twoe'
      preLoaderRoute: typeof TwoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timing': {
      id: '/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof TimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spark': {
      id: '/spark'
      path: '/spark'
      fullPath: '/spark'
      preLoaderRoute: typeof SparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loom': {
      id: '/loom'
      path: '/loom'
      fullPath: '/loom'
      preLoaderRoute: typeof LoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twoe/': {
      id: '/twoe/'
      path: '/'
      fullPath: '/twoe/'
      preLoaderRoute: typeof TwoeIndexRouteImport
      parentRoute: typeof TwoeRoute
    }
    '/spark/': {
      id: '/spark/'
      path: '/'
      fullPath: '/spark/'
      preLoaderRoute: typeof SparkIndexRouteImport
      parentRoute: typeof SparkRoute
    }
    '/loom/': {
      id: '/loom/'
      path: '/'
      fullPath: '/loom/'
      preLoaderRoute: typeof LoomIndexRouteImport
      parentRoute: typeof LoomRoute
    }
    '/twoe/results': {
      id: '/twoe/results'
      path: '/results'
      fullPath: '/twoe/results'
      preLoaderRoute: typeof TwoeResultsRouteImport
      parentRoute: typeof TwoeRoute
    }
    '/twoe/assessment': {
      id: '/twoe/assessment'
      path: '/assessment'
      fullPath: '/twoe/assessment'
      preLoaderRoute: typeof TwoeAssessmentRouteImport
      parentRoute: typeof TwoeRoute
    }
    '/spark/reflect': {
      id: '/spark/reflect'
      path: '/reflect'
      fullPath: '/spark/reflect'
      preLoaderRoute: typeof SparkReflectRouteImport
      parentRoute: typeof SparkRoute
    }
    '/spark/mirror': {
      id: '/spark/mirror'
      path: '/mirror'
      fullPath: '/spark/mirror'
      preLoaderRoute: typeof SparkMirrorRouteImport
      parentRoute: typeof SparkRoute
    }
    '/spark/currents': {
      id: '/spark/currents'
      path: '/currents'
      fullPath: '/spark/currents'
      preLoaderRoute: typeof SparkCurrentsRouteImport
      parentRoute: typeof SparkRoute
    }
    '/loom/constellation': {
      id: '/loom/constellation'
      path: '/constellation'
      fullPath: '/loom/constellation'
      preLoaderRoute: typeof LoomConstellationRouteImport
      parentRoute: typeof LoomRoute
    }
  }
}

interface LoomRouteChildren {
  LoomConstellationRoute: typeof LoomConstellationRoute
  LoomIndexRoute: typeof LoomIndexRoute
}

const LoomRouteChildren: LoomRouteChildren = {
  LoomConstellationRoute: LoomConstellationRoute,
  LoomIndexRoute: LoomIndexRoute,
}

const LoomRouteWithChildren = LoomRoute._addFileChildren(LoomRouteChildren)

interface SparkRouteChildren {
  SparkCurrentsRoute: typeof SparkCurrentsRoute
  SparkMirrorRoute: typeof SparkMirrorRoute
  SparkReflectRoute: typeof SparkReflectRoute
  SparkIndexRoute: typeof SparkIndexRoute
}

const SparkRouteChildren: SparkRouteChildren = {
  SparkCurrentsRoute: SparkCurrentsRoute,
  SparkMirrorRoute: SparkMirrorRoute,
  SparkReflectRoute: SparkReflectRoute,
  SparkIndexRoute: SparkIndexRoute,
}

const SparkRouteWithChildren = SparkRoute._addFileChildren(SparkRouteChildren)

interface TwoeRouteChildren {
  TwoeAssessmentRoute: typeof TwoeAssessmentRoute
  TwoeResultsRoute: typeof TwoeResultsRoute
  TwoeIndexRoute: typeof TwoeIndexRoute
}

const TwoeRouteChildren: TwoeRouteChildren = {
  TwoeAssessmentRoute: TwoeAssessmentRoute,
  TwoeResultsRoute: TwoeResultsRoute,
  TwoeIndexRoute: TwoeIndexRoute,
}

const TwoeRouteWithChildren = TwoeRoute._addFileChildren(TwoeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoomRoute: LoomRouteWithChildren,
  MapRoute: MapRoute,
  ModesRoute: ModesRoute,
  ReflectionsRoute: ReflectionsRoute,
  SnapshotsRoute: SnapshotsRoute,
  SparkRoute: SparkRouteWithChildren,
  TimingRoute: TimingRoute,
  TwoeRoute: TwoeRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
