/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TimingRouteImport } from './routes/timing'
import { Route as SparkRouteImport } from './routes/spark'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SparkIndexRouteImport } from './routes/spark.index'
import { Route as SparkReflectRouteImport } from './routes/spark.reflect'
import { Route as SparkMirrorRouteImport } from './routes/spark.mirror'
import { Route as SparkCurrentsRouteImport } from './routes/spark.currents'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingRoute = TimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkRoute = SparkRouteImport.update({
  id: '/spark',
  path: '/spark',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkIndexRoute = SparkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SparkRoute,
} as any)
const SparkReflectRoute = SparkReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => SparkRoute,
} as any)
const SparkMirrorRoute = SparkMirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => SparkRoute,
} as any)
const SparkCurrentsRoute = SparkCurrentsRouteImport.update({
  id: '/currents',
  path: '/currents',
  getParentRoute: () => SparkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/modes': typeof ModesRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/spark': typeof SparkRouteWithChildren
  '/timing': typeof TimingRoute
  '/workflows': typeof WorkflowsRoute
  '/spark/currents': typeof SparkCurrentsRoute
  '/spark/mirror': typeof SparkMirrorRoute
  '/spark/reflect': typeof SparkReflectRoute
  '/spark/': typeof SparkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/modes': typeof ModesRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/timing': typeof TimingRoute
  '/workflows': typeof WorkflowsRoute
  '/spark/currents': typeof SparkCurrentsRoute
  '/spark/mirror': typeof SparkMirrorRoute
  '/spark/reflect': typeof SparkReflectRoute
  '/spark': typeof SparkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/modes': typeof ModesRoute
  '/reflections': typeof ReflectionsRoute
  '/snapshots': typeof SnapshotsRoute
  '/spark': typeof SparkRouteWithChildren
  '/timing': typeof TimingRoute
  '/workflows': typeof WorkflowsRoute
  '/spark/currents': typeof SparkCurrentsRoute
  '/spark/mirror': typeof SparkMirrorRoute
  '/spark/reflect': typeof SparkReflectRoute
  '/spark/': typeof SparkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/modes'
    | '/reflections'
    | '/snapshots'
    | '/spark'
    | '/timing'
    | '/workflows'
    | '/spark/currents'
    | '/spark/mirror'
    | '/spark/reflect'
    | '/spark/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/modes'
    | '/reflections'
    | '/snapshots'
    | '/timing'
    | '/workflows'
    | '/spark/currents'
    | '/spark/mirror'
    | '/spark/reflect'
    | '/spark'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/modes'
    | '/reflections'
    | '/snapshots'
    | '/spark'
    | '/timing'
    | '/workflows'
    | '/spark/currents'
    | '/spark/mirror'
    | '/spark/reflect'
    | '/spark/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  ModesRoute: typeof ModesRoute
  ReflectionsRoute: typeof ReflectionsRoute
  SnapshotsRoute: typeof SnapshotsRoute
  SparkRoute: typeof SparkRouteWithChildren
  TimingRoute: typeof TimingRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timing': {
      id: '/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof TimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spark': {
      id: '/spark'
      path: '/spark'
      fullPath: '/spark'
      preLoaderRoute: typeof SparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spark/': {
      id: '/spark/'
      path: '/'
      fullPath: '/spark/'
      preLoaderRoute: typeof SparkIndexRouteImport
      parentRoute: typeof SparkRoute
    }
    '/spark/reflect': {
      id: '/spark/reflect'
      path: '/reflect'
      fullPath: '/spark/reflect'
      preLoaderRoute: typeof SparkReflectRouteImport
      parentRoute: typeof SparkRoute
    }
    '/spark/mirror': {
      id: '/spark/mirror'
      path: '/mirror'
      fullPath: '/spark/mirror'
      preLoaderRoute: typeof SparkMirrorRouteImport
      parentRoute: typeof SparkRoute
    }
    '/spark/currents': {
      id: '/spark/currents'
      path: '/currents'
      fullPath: '/spark/currents'
      preLoaderRoute: typeof SparkCurrentsRouteImport
      parentRoute: typeof SparkRoute
    }
  }
}

interface SparkRouteChildren {
  SparkCurrentsRoute: typeof SparkCurrentsRoute
  SparkMirrorRoute: typeof SparkMirrorRoute
  SparkReflectRoute: typeof SparkReflectRoute
  SparkIndexRoute: typeof SparkIndexRoute
}

const SparkRouteChildren: SparkRouteChildren = {
  SparkCurrentsRoute: SparkCurrentsRoute,
  SparkMirrorRoute: SparkMirrorRoute,
  SparkReflectRoute: SparkReflectRoute,
  SparkIndexRoute: SparkIndexRoute,
}

const SparkRouteWithChildren = SparkRoute._addFileChildren(SparkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  ModesRoute: ModesRoute,
  ReflectionsRoute: ReflectionsRoute,
  SnapshotsRoute: SnapshotsRoute,
  SparkRoute: SparkRouteWithChildren,
  TimingRoute: TimingRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
